# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

[variables]
account_id = 658786808637
cluster_name = "test0"
domain_name = "aws.noa.re"
aws_region = "eu-west-2"
k8s_service_host = "4A7E67A22254B2F6FB8C887F1882DEBA.gr7.eu-west-2.eks.amazonaws.com"

[[helm]]
namespace = "teleport-cluster"
release = "teleport-cluster"
values = ["teleport/cluster-values.yaml"]
extra-resources = "teleport/extra"

[[helm]]
namespace = "kube-system"
release = "aws-load-balancer-controller"
values = ["aws-load-balancer-controller/values.yaml"]
extra-resources = "aws-load-balancer-controller/extra"

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = ["cert-manager/values.yaml"]
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "external-dns"
release = "external-dns"
values = ["external-dns/values.yaml"]
extra-resources = "external-dns/extra"

[[helm]]
namespace = "teleport"
release = "teleport-kube-agent"
values = ["teleport/agent-values.yaml"]

[[helm]]
namespace = "karpenter"
release = "karpenter"
values = ["karpenter/values.yaml"]
extra-resources = "karpenter/extra"

[[helm]]
namespace = "cilium"
release = "cilium"
values = ["cilium/values.yaml"]
extra-resources = "cilium/extra"

[[helm]]
namespace = "argo"
release = "argocd"
values = ["argocd/values.yaml"]

[[helm]]
namespace = "metrics-server"
release = "metrics-server"
