# SPDX-FileCopyrightText: 2026 The clusterspinner contributors
# SPDX-License-Identifier: MIT

repositories:
  - name: teleport
    url: https://charts.releases.teleport.dev
  - name: eks
    url: https://aws.github.io/eks-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: karpenter
    url: public.ecr.aws/karpenter
    oci: true
  - name: cilium
    url: quay.io/cilium/charts
    oci: true
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: teleport-cluster
    chart: teleport/teleport-cluster
    version: 18.7.6

  - name: teleport-kube-agent
    chart: teleport/teleport-kube-agent
    version: 18.7.6

  - name: aws-load-balancer-controller
    chart: eks/aws-load-balancer-controller
    version: 3.2.2

  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.20.2

  - name: external-dns
    chart: external-dns/external-dns
    version: 1.21.1

  - name: karpenter
    chart: karpenter/karpenter
    version: 1.12.0

  - name: cilium
    chart: cilium/cilium
    version: 1.19.4

  - name: argocd
    chart: argo/argo-cd
    version: 9.5.11
